version: '3.2'

services:
  api1:
    container_name: api1
    build: ./api1
    depends_on:
      - api2
    volumes:
      - './api1:/usr/src/app'
    ports:
      - "3000:3000"
  api2:
    container_name: api2
    build: ./api2
    volumes:
      - './api2:/usr/src/app'
    ports:
      - "8000:8000"
  zookeeper:
    container_name: zookeeper
    image: 'bitnami/zookeeper:latest'
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"
    ports:
      - 2181:2181
      - 2888:2888
      - 3888:3888
  kafka:
    container_name: kafka
    image: 'bitnami/kafka:latest'
    depends_on:
      - zookeeper
    environment:
      KAFKA_ADVERTISED_HOST_NAME: "kafka"
      KAFKA_ADVERTISED_PORT: "9092"
      ALLOW_PLAINTEXT_LISTENER: "yes"
      KAFKA_CFG_ZOOKEEPER_CONNECT: "zookeeper:2181"
    ports:
      - 9092:9092
